# Streamlit Secrets Configuration
# This file shows the format for adding your API key in Streamlit Cloud

# To add your API key in Streamlit Cloud:
# 1. Go to your app dashboard
# 2. Click Settings → Secrets  
# 3. Add this line (without the # comment):

# ANTHROPIC_API_KEY = "your-api-key-here"

# Note: The app works perfectly without an API key in "Smart Analytics Mode"
# Add the key later when your repository is private for "AI Enhanced Mode"